### ISSUE TITLE
Bad performance over LFN

### ISSUE THREAD

**Issue by hotpxl** [bigeagle/gohop#12]
I'm running gohop across a long fat pipe and I'm getting bad performance. Usually when I rsync a file on one side from the other side I can reach up to 600 KB/s, but using gohop I can only reach 60 KB/s. I don't think gohop itself is using TCP so there would be no flow control problem. And RTT with and without gohop are approximately the same (~400ms). Both machines have a pretty light CPU load and memory usage. I guess there is a huge packet loss somewhere but I don't know how to diagnose. Do you have any suggestion where I should start digging into this issue?

**Comment by HexValid** [comment]
Same issue here.
