### ISSUE TITLE
"go get github.com/bigeagle/water" on win7x64 

### ISSUE THREAD

**Issue by paway** [bigeagle/gohop#3]
go version
go version go1.2 windows/amd64
set GOPATH=D:\Go\src
go get github.com/bigeagle/water
# github.com/bigeagle/water

D:\Go\src\src\github.com\bigeagle\water\if.go:22: undefined: createInterface
D:\Go\src\src\github.com\bigeagle\water\if.go:22: undefined: cIFF_TAP
D:\Go\src\src\github.com\bigeagle\water\if.go:22: undefined: cIFF_NO_PI
D:\Go\src\src\github.com\bigeagle\water\if.go:38: undefined: createInterface
D:\Go\src\src\github.com\bigeagle\water\if.go:38: undefined: cIFF_TUN
D:\Go\src\src\github.com\bigeagle\water\if.go:38: undefined: cIFF_NO_PI

**Comment by tlindquist** [comment]
What is performance like on beaglebone black? I might get one to try.

**Comment by bigeagle** [comment]
I'm running it on BBB well

**Comment by tlindquist** [comment]
Got a Beaglebone Black to try. Can you clarify the server/client configuration. Is Beaglebone black running as server? Do we also need to run desktop as a gohop client then? Or does server have to sit outside the GFW? It's a little unclear from the read me.

**Comment by dgrr** [comment]
Close this issue. Thanks.
